### ISSUE TITLE
[DOC] Add installation instructions

### ISSUE THREAD

**Issue by ThibTrip** [minrk/allthekernels#13]
Hello, since it seems we cannot do PRs I would like to propose some installation instructions (I could not find them anywhere) to add in the README.md in this issue:

```markdown
# Installation

1. Download and extract the contents of this repository or clone it (<code>git clone https://github.com/minrk/allthekernels.git</code>).

2. Navigate to the cloned/extracted repository folder.

3. Install with <code>pip install .</code> (or <code>pip3</code> instead of <code>pip</code> in Linux)
```

**Comment by minrk** [comment]
Hi, thanks for contributing! What is the issue with PRs that you are seeing?

Installation instructions are the same as for all Python packages, so by default should be only:

    python3 -m pip install allthekernels

Or to do a dev install from source:

    python3 -m pip install [-e] .

Happy to have a PR adding the above.

**Comment by ThibTrip** [comment]
It says I don't have acess to the repo. I cloned it and then tried with GitHub desktop first and then with cmd and both failed I can't push my branch.

# GitHub desktop
![pr_problem](https://user-images.githubusercontent.com/40694343/83261020-013db900-a1bb-11ea-8cf6-6dd51d68b9aa.png)

# cmd
![pr_problem2](https://user-images.githubusercontent.com/40694343/83261019-00a52280-a1bb-11ea-9146-1f02044e2f68.png)

**Comment by minrk** [comment]
Yup, that's true in general on GitHub. Only people with write access to a repo can push to branches on it. The way you make a pull request is to first fork the repo and push to a branch on your fork, then issue the PR from your branch on your fork. Check out the [GitHub docs on pull requests](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) for more info.
