### ISSUE TITLE
Make cell blocking

### ISSUE THREAD

**Issue by davidbrochart** [minrk/allthekernels#16]
Thanks for this great "meta"-kernel!
One thing though, when executing two consecutive cells which use a different kernel, the second cell won't wait for the first one to finish, if the kernel of the second cell is not busy. In other words, the execution state is per kernel.
While that may be useful in some situations, would it be possible to optionally block the execution until all kernels are idle?

**Comment by SylvainCorlay** [comment]
:+1: this is the main issue that we are seeing with `allthekernels`!

**Comment by minrk** [comment]
Yeah, definitely makes sense. I think reworking the relay_to_kernel to also wait for replies should work for this.
