### ISSUE TITLE
TSLab version 1.0.21 not working properly with AllTheKernels kernel version 1.2.0

### ISSUE THREAD

**Issue by paolocarinci** [minrk/allthekernels#24]
Whenever you execute a command in [AllTheKernels kernel](https://github.com/minrk/allthekernels) (either in a notebook or in a shell), e.g.

```
>jslab
console.log("Test");
```

the cell remains running indefinitley and no output is shown.
In the logs I spotted an error message that says that a JSON parse exception has occurred.

```
[AllTheKernelsApp] Relaying execute_request to jslab
UnhandledPromiseRejection: SyntaxError: Unexpected token 'a', "a07332d4ce"... is not valid JSON
    at JSON.parse (<anonymous>)
    at ZmqMessage.fromRaw (/opt/jupyterhub/lib/node_modules/tslab/dist/jupyter.js:67:27)
    at ZmqServer.handleShellMessage (/opt/jupyterhub/lib/node_modules/tslab/dist/jupyter.js:315:32)
    at /opt/jupyterhub/lib/node_modules/tslab/dist/jupyter.js:435:30
```

while the AllTheKernels kernel works fine with all the other kernels I use (IPython, Gophernotes, Bash, C, IJava).

**Comment by minrk** [comment]
Thanks for the message, this is a bug in tslab, as you've [already reported](https://github.com/yunabe/tslab/issues/98). Should be fixed by https://github.com/yunabe/tslab/pull/99

**Comment by yunabe** [comment]
Thank you for the fix, Min. I merged your pull request and pushed the new version.
